spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hoteldb
    username: hoteluser
    password: hotelpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  thymeleaf:
    cache: false
server:
  error:
    whitelabel:
      enabled: false
  port: 8080 